### PR TITLE
keep name of plugin iso eNiro + English

### PR DESCRIPTION
**Pull request by JanJaapKo**
The current version had some Dutch names, changed that to English
Secondly it used 'eNiro' in the automatically updated device names, while I have a Kona..... I made that depending on the default prefix. Will add some error handling there later on

### CODE REVIEW

**Comment by PierreLevres** [comment]
I’ll accept your changes. I’ve been redesigning the core python code for the API into a more object-oriented approach. This has not been integrated into the plugin yet, just into the debug.py. See https://github.com/PierreLevres/BlUVO/tree/object_orientation <https://github.com/PierreLevres/BlUVO/tree/object_orientation>

Furthermore something other to consider: Since I am not very fond of Domoticz web-interface I am thinking about releasing a more general plugin with Node-Red and MQTT interfacing to the BlueLinky java code. That code is maintained by a bigger group of developers. There would no longer be a need for any logic in the plugin, just for some (virtual) devices. MQTT is available from Domoticz. Node-Red is easily run next to domoticz. So i think the lib will be available to take over maintenance soon.

**Comment by JanJaapKo** [comment]
Hi @PierreLevres 
I noticed indeed the lack of OO in the plugin. 

When looking for a good integration with an external application, you may wanna have a look into [Zigbee2Mqtt](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin). Its pretty cool, as it also comes with its own config page under the custom menu of domoticz

**Comment by JanJaapKo** [comment]
I did some more cosmetic changes:
- replaced the 'distance from home' with a text sensor, so the URL ends up in the value field iso the name, which prevents it from being added to the GUI
- added hood

**Comment by JanJaapKo** [comment]
@PierreLevres I added some other cosmetic stuff to the widgets

**Comment by PierreLevres** [comment]
Development and maintenance stopped. Feel free to fork and adjust the code yourself.

**Pull request merged**
